# 完整医疗数据UDA分析配置文件

# 实验基本配置
experiment:
  name: "complete_medical_uda_analysis"
  description: "完整的医疗数据UDA分析流程：源域CV + UDA方法对比 + 可视化"
  random_state: 42
  verbose: true

# 数据预处理配置
preprocessing:
  feature_set: "best8"         # 特征集选择: best7|best8|best9|best10|all
  scaler: "standard"           # 标准化方法: standard|robust|none
  imbalance_method: "smote"    # 不平衡处理: none|smote|smotenc|borderline_smote|kmeans_smote|svm_smote|adasyn|smote_tomek|smote_enn|random_under
  force_resampling: false      # 是否强制执行重采样（测试模式）

# 源域交叉验证配置
source_domain:
  cv_folds: 10
  models:
    - "tabpfn"
    - "paper_method"
    - "pkuph_baseline"
    - "mayo_baseline"

# UDA方法配置
uda_methods:
  # 实例重加权方法
  instance_based:
    - method: "KMM"
      params:
        kernel: "rbf"
        gamma: 1.0
    - method: "KLIEP"
      params:
        gamma: 1.0
        
  # 特征对齐方法
  feature_based:
    - method: "CORAL"
      params:
        lambda_: 1.0
    - method: "SA"
      params:
        n_components: null
    - method: "TCA"
      params:
        n_components: 6
        mu: 0.1
        kernel: "linear"
    - method: "FMMD"
      params:
        gamma: 1.0

# 评估配置
evaluation:
  metrics:
    - "auc"          # 主要指标
    - "accuracy"
    - "f1"
    - "precision"
    - "recall"
  comparison_baseline: true    # 是否包含无DA的基线对比
  
# 可视化配置
visualization:
  enable_pca: true
  enable_tsne: true
  enable_distance_metrics: true
  skip_feature_distributions: true  # 跳过特征分布可视化
  save_individual_plots: true
  plot_format: "png"
  figsize: [16, 12]
  
# 输出配置
output:
  results_dir: "results"
  save_preprocessed_data: true
  save_model_predictions: true
  save_visualization_data: true
  generate_html_report: true
  generate_markdown_report: true

# TabPFN模型配置
tabpfn:
  n_estimators: 32
  categorical_features_indices: null
  softmax_temperature: 0.9
  balance_probabilities: false
  average_before_softmax: false
  model_path: "auto"
  device: "auto"
  ignore_pretraining_limits: true
  inference_precision: "auto"
  fit_mode: "fit_preprocessors"
  memory_saving_mode: "auto"
  n_jobs: -1 